config/routes.rb
Rails.application.routes.draw do
  get '/oauth_apply' => 'application#oauth_apply_callback_generator'

  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}

  resources :user_profiles, only: [:new, :create]
  resources :job_postings
  resources :booking_access_tokens, only: [:new, :create, :show, :index] do
    collection do
      get :signup
    end
  end
  resource :wifi, only: [:show, :update], controller: 'wifi'

  scope 'membership_payments', controller: :membership_payments do
    post 'stripe_webhook'
    post 'capture_single'
    post 'capture_subscription'
    post 'process_cancel_subscription'
    get 'payment_confirmation'
    get 'pay_single'
    get 'cancel_subscription'
  end

  resources :membership_requests, only: [:new, :show, :create] do
    member do
      MembershipRequest.workflow_spec.states.keys.each do |state|
        get "stage/#{state}" => "membership_requests#workflow_#{state}", as: "workflow_#{state}"
        post "stage/#{state}" => "membership_requests#workflow_#{state}", as: "workflow_submit_#{state}"
      end
    end
  end

  namespace :api do
    resources :users, only: [:index]
  end

  get 'booking/:name/new' => 'booking#new'
  post 'booking/:name/pay' => 'booking#pay'
  get 'booking/:id/confirmation' => 'booking#confirmation'

  scope 'api', controller: :api do
    get 'st_cats_admin' => 'api#profiles_csv'
    post 'user_auth_token'
    post 'profiles/:id' => 'api#get_profile_info'
    post 'profiles/:id/update' => 'api#update_profile_info'
    #get 'profiles/:id/profile_image_upload_url' => 'api#profile_image_upload_url'
  end

  get '/admin/membership_requests/:id', to: redirect('/admin/membership_request/%{id}') # Backwards compatibility
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'dashboard' => 'welcome#dashboard'
  root 'welcome#index'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_authorization_check
  before_action :authenticate_user!, except: [:index]

  def index
    if current_user
      redirect_to dashboard_path
    end
  end

  def dashboard
    @active_memberships = current_user.active_memberships
    @active_applications = current_user.membership_requests.where.not(closed: true)
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/dashboard.html.erb
<% unless current_user.staff? %>
    <h1>Your Dashboard</h1>

    <p>Hi, I'm your dashboard. Am I full? Am I empty? I don't know, my coders haven't implemented that level of
      self-awareness yet. For now, I can give you the general advice - start a new application or continue an existing
      application here.</p>

    <% if @active_applications.any? %>
        <h2>Active Applications / Memberships</h2>
        <% @active_applications.each do |request| %>
            <% if not request.cancelled? and not request.expired? %>
                <%= link_to "#{request.membership_type.name}", request %>
                <% if request.active_membership? and request.has_subscription? %>
                    (<%= link_to 'Cancel subscription', action: 'cancel_subscription', controller: 'membership_payments', :membership_request_id => request.id %>)
                    <br>
                <% end %>
            <% end %>
        <% end %>
        <br><br>
    <% end %>

    <% unless @active_memberships.any? %>
        <%= button_to 'Apply to be a member', new_membership_request_path, method: 'get', id: 'dashboard_apply_to_be_a_member' %>
    <% end %>

<% else %>
    <p>This is a staff account, you can't apply for anything :(</p>
    <% if current_user.manager? %>
        <%= link_to 'Manage booking tokens', booking_access_tokens_path %>
    <% end %>
<% end %>

app/views/welcome/index.html.erb
<h1>Hello &amp; Welcome to Bloom</h1>

<p>Looks like you're interested in joining Bloom - good choice! We make starting stuff and being entrepreneurial much easier for young Western Australians, university students and recent grads.</p>
<p>To start or continue an application to become a Bloom co-working member, please sign-up or log in.</p>

<button style="margin-left: auto;margin-right: auto;display: block;background-color:#D50F25;" onclick="location.href='<%= user_omniauth_authorize_path(:google_oauth2) %>'">Log in with Google</button>