config/routes.rb
Rails.application.routes.draw do
  get '/oauth_apply' => 'application#oauth_apply_callback_generator'

  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}

  resources :user_profiles, only: [:new, :create]
  resources :job_postings
  resources :booking_access_tokens, only: [:new, :create, :show, :index] do
    collection do
      get :signup
    end
  end
  resource :wifi, only: [:show, :update], controller: 'wifi'

  scope 'membership_payments', controller: :membership_payments do
    post 'stripe_webhook'
    post 'capture_single'
    post 'capture_subscription'
    post 'process_cancel_subscription'
    get 'payment_confirmation'
    get 'pay_single'
    get 'cancel_subscription'
  end

  resources :membership_requests, only: [:new, :show, :create] do
    member do
      MembershipRequest.workflow_spec.states.keys.each do |state|
        get "stage/#{state}" => "membership_requests#workflow_#{state}", as: "workflow_#{state}"
        post "stage/#{state}" => "membership_requests#workflow_#{state}", as: "workflow_submit_#{state}"
      end
    end
  end

  namespace :api do
    resources :users, only: [:index]
  end

  get 'booking/:name/new' => 'booking#new'
  post 'booking/:name/pay' => 'booking#pay'
  get 'booking/:id/confirmation' => 'booking#confirmation'

  scope 'api', controller: :api do
    get 'st_cats_admin' => 'api#profiles_csv'
    post 'user_auth_token'
    post 'profiles/:id' => 'api#get_profile_info'
    post 'profiles/:id/update' => 'api#update_profile_info'
    #get 'profiles/:id/profile_image_upload_url' => 'api#profile_image_upload_url'
  end

  get '/admin/membership_requests/:id', to: redirect('/admin/membership_request/%{id}') # Backwards compatibility
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'dashboard' => 'welcome#dashboard'
  root 'welcome#index'
end

app/models/membership_request.rb
class MembershipRequest < ActiveRecord::Base
  include Workflow
  scope :pending_decision, -> { where(workflow_state: 'pending_decision') }

  has_paper_trail

  belongs_to :user
  belongs_to :membership_type

  validates :user_id, presence: true
  validates :membership_type_id, presence: true
  validate :only_one_open_application

  def only_one_open_application
    if MembershipRequest.where(user_id: user_id, closed: false, membership_type_id: membership_type_id).where.not(id: id).count != 0
      errors.add(:base, "Sorry, it looks like you have already applied to become that type of Bloom member. If you think this is a mistake, please <a href='mailto:#{Rails.configuration.x.help_contact.email}'>email #{Rails.configuration.x.help_contact.name}</a>.")
    end
  end

  after_create :autoapprove_check

  # We advance the application to the payment stage if autoapprove is on for the given membership type
  def autoapprove_check
    if membership_type.autoapprove?
      autoapprove!
    end
  end

  def delete_subscription
    if !self.stripe_subscription_id.nil?
      stripe_subscription.delete
    end
    self.stripe_subscription_id = nil
  end

  def stripe_subscription
    self.user.stripe_customer.subscriptions.retrieve(self.stripe_subscription_id)
  end

  def has_subscription?
    !self.stripe_subscription_id.nil? and workflow_state == 'active_membership'
  end

  def set_subscription!(customer, plan_id)
    sub = customer.subscriptions.create(
        :plan => plan_id
    )
    self.stripe_subscription_id = sub.id
  end

  workflow do
    state :new do
      event :submit, transitions_to: :pending_decision
      event :cancel, transitions_to: :cancelled
      event :autoapprove, transitions_to: :payment_required
    end

    state :book_interview do
      event :book, transitions_to: :pending_decision
      event :cancel, transitions_to: :cancelled
    end

    state :pending_decision do
      event :accept, transitions_to: :payment_required
      event :reject, transitions_to: :rejected
      event :cancel, transitions_to: :cancelled
    end

    state :payment_required do
      event :pay, transitions_to: :active_membership
      event :cancel, transitions_to: :cancelled
    end

    state :active_membership do
      event :payment_fail, transitions_to: :payment_required
      event :expire, transitions_to: :expired
      event :cancel, transitions_to: :cancelled
    end

    state :rejected
    state :cancelled
    state :expired
  end

  def can_cancel?
    self.current_state.events.include?(:cancel) and self.current_state != :active_membership
  end

  def autoapprove
    puts 'TODO: Autoapprove yay!'
  end

  def book
    MembershipRequestsMailer.delay.new_membership_request(self)
  end

  def accept
    Heap.track 'Membership Request Approved', self.user.heap_identifier, application_membership_type: self.membership_type.stripe_id
  end

  def pay
    MembershipRequestsMailer.delay.coworking_confirmation(self)
    Heap.track 'Membership Request Paid', self.user.heap_identifier, current_membership_type: self.membership_type.stripe_id
  end

  def payment_fail
    puts 'TODO: Uh oh ya messed up'
  end

  def notify
    MembershipRequestsMailer.delay.new_membership_request(self)
  end

  def cancel
    Heap.track 'Membership Request Cancelled', self.user.heap_identifier
    update_attribute(:closed, true)

    if self.current_state == :active_membership
      Heap.track 'Active Membership Cancelled', self.user.heap_identifier, current_membership_type: ''
      MembershipRequestsMailer.delay.cancelled_membership(self)
    end
  end

  def expire
    update_attribute(:closed, true)

    puts 'TODO: Expired!!!'
  end

  def reject
    update_attribute(:closed, true)

    MembershipRequestsMailer.delay.request_rejected(self)
  end

  def workflow_state_enum
    self.class.workflow_spec.state_names
  end

  def on_payment_required_entry(*args)
    if self.membership_type.price > 0
      MembershipRequestsMailer.delay.request_accepted(self) # Send payment required email
    else
      self.pay! # If the membership is free, we skip the payment required phase
    end
  end

  rails_admin do
    list do
      scopes [nil, :pending_decision]
      sort_by :user
      field :user do
        sortable 'firstname, lastname'
      end
      field :membership_type
      field :workflow_state
    end
    show do
      field :user
      field :membership_type
      field :workflow_state
      field :info
      field :startdate
      field :interview_book_info
      field :cancel_reason
      field :created_at
    end
  end
end

app/controllers/membership_requests_controller.rb
class MembershipRequestsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_membership_request, only: [:show, :update, :destroy]
  before_action :workflow_redirect
  before_action :ensure_user_profile, except: [:new, :create]

  # GET /membership_requests/1
  # GET /membership_requests/1.json
  def show
    # We redirect the person to the current step in their workflow
    redirect_to url_for(controller: 'membership_requests',
                        action: "workflow_#{@membership_request.workflow_state}",
                        id: @membership_request.id)
  end

  # GET /membership_requests/new
  def new
    redirect_to 'http://www.bloom.org.au/apply/'
  end

  # POST /membership_requests
  # POST /membership_requests.json
  def create
    @membership_request = current_user.membership_requests.build(membership_request_params)

    #TODO
    #Check the fields of the form to make sure they are legit by placing rules in the model

    respond_to do |format|
      if @membership_request.save
        format.html { redirect_to membership_request_path(@membership_request.id) }
        # Email bloom admin - or account notification or something...
        format.json { render :show, status: :created, location: @membership_request }
      else
        format.html { render :new }
        format.json { render json: @membership_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # Workflow views

  def workflow_new
    if request.post?
      @membership_request.info = params[:info]
      @membership_request.startdate = Date.new(*params['startdate'].values.map(&:to_i))


      if @membership_request.info.blank?
        redirect_to membership_request_path(@membership_request), flash: {error: 'Please include some info about your startup'}
        return
      end

      if @membership_request.startdate.mon < Date.today.mon
        @membership_request.startdate = nil
        @membership_request.save!
        redirect_to membership_request_path(@membership_request), flash: {error: 'Please choose a date in the future'}
        return
      end

      @membership_request.save!
      @membership_request.submit!
      redirect_to membership_request_path(@membership_request)
    end
  end

  def workflow_book_interview
    if request.post?
      @membership_request.interview_book_info = params[:interview_book_info]
      @membership_request.save!

      @membership_request.book!
      redirect_to membership_request_path(@membership_request)
    end
  end

  def workflow_pending_decision
    graph = Koala::Facebook::API.new(Rails.configuration.facebook[:app_token])
    events = graph.get_connections('BloomPerth', "events?since=#{Time.now.to_i}")
    @next_pitching_night = nil
    @next_leancanvas_night = nil
    @next_preparing_to_pitch_night = nil
    @membership_type = @membership_request.membership_type
    now = DateTime.now
    while true
      events.each do |event|
        dt = DateTime.parse(event['start_time'])
        return if now > dt
        name = event['name'].downcase
        if name.include? 'pitching night' and (@next_pitching_night.nil? or dt < DateTime.parse(@next_pitching_night['start_time']))
          @next_pitching_night = event
        elsif name.include? 'prepare to pitch' and (@next_preparing_to_pitch_night.nil? or dt < DateTime.parse(@next_preparing_to_pitch_night['start_time']))
          @next_preparing_to_pitch_night = event
        elsif name.include? 'lean canvas' and (@next_leancanvas_night.nil? or dt < DateTime.parse(@next_leancanvas_night['start_time']))
          @next_leancanvas_night = event
        end
      end
      if events.respond_to? :next_page and not events.next_page.nil?
        events = events.next_page
      else
        break
      end
    end
  end

  def workflow_payment_required
    @membership_type = @membership_request.membership_type
  end

  def workflow_active_membership

  end

  def workflow_rejected

  end

  def workflow_cancelled

  end

  def workflow_expired

  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_membership_request
    @membership_request = MembershipRequest.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def membership_request_params
    params.require(:membership_request).permit(:membership_type_id, :startdate)
  end

  # Make sure user can only go to the stage of the workflow that they're on
  def workflow_redirect
    if action_name.starts_with?('workflow_')
      state = @membership_request.workflow_state

      if action_name != 'workflow_' + state
        redirect_to url_for(controller: 'membership_requests',
                            action: "workflow_#{@membership_request.workflow_state}",
                            id: @membership_request.id)
      end
    end
  end

  # Make sure user has filled out user_profile before continuing
  def ensure_user_profile
    if not current_user.user_profiles.any?
      session[:user_profile_return_to] ||= request.original_fullpath
      redirect_to new_user_profile_path, notice: 'Before continuing, can you tell us a bit more about yourself?'
    end
  end
end

app/helpers/membership_requests_helper.rb
module MembershipRequestsHelper
end

app/views/membership_requests/_workflow_footer.html.erb
<% if @membership_request.can_cancel? %>
    <br><br>

    <p><%= link_to 'Cancel Request', @membership_request, method: :delete, data: { confirm: 'Are you sure?' } %></p>
<% elsif @membership_request.current_state == :active_membership %>
    <br><br>

    <p><%= link_to "Cancel subscription", action: 'cancel_subscription', controller: 'membership_payments', :membership_request_id => @membership_request.id %></p>
<% end %>

app/views/membership_requests/_workflow_header.html.erb
<h1>Application: <%= @membership_request.membership_type.name %></h1>

app/views/membership_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @membership_request.user.display_name %>
</p>

<p>
  <strong>Membership:</strong>
  <%= @membership_request.membership_type.name %>
</p>

<p>
  <strong>Startdate:</strong>
  <%= @membership_request.startdate %>
</p>

<p>
  <strong>Application status:</strong>
  <%= @membership_request.workflow_state %>
</p>

<%= link_to 'Edit', edit_membership_request_path(@membership_request) %> |
<%= link_to 'Back', membership_requests_path %>

app/views/membership_requests/workflow_active_membership.html.erb
<%= render 'workflow_header' %>

<p>Your membership is currently active.</p>

<p>To make changes to your payment information, please <a href="mailto:<%= Rails.configuration.x.help_contact.email %>">contact <%= Rails.configuration.x.help_contact.name %></a>.</p>

<%= render 'workflow_footer' %>

app/views/membership_requests/workflow_book_interview.html.erb
<%= render 'workflow_header' %>

<%= form_tag do %>
    <div class="field">
      <p>Please let us know a few times you're available for an interview in the two weeks before your expected start date</p>
      <p>We will be in touch to confirm your interview time</p>
      <%= text_area_tag(:interview_book_info) %>
    </div>

    <%= submit_tag('Submit') %>
<% end %>

<%= render 'workflow_footer' %>

app/views/membership_requests/workflow_cancelled.html.erb
<%= render 'workflow_header' %>

<p>This membership request has been cancelled.</p>

<p>You may apply for a new membership type from <%= link_to 'the dashboard', dashboard_path %>.</p>

<%= render 'workflow_footer' %>

app/views/membership_requests/workflow_current.html.erb
<%= render 'workflow_header' %>

<p>Stuff</p>

<%= render 'workflow_footer' %>

app/views/membership_requests/workflow_expired.html.erb
<%= render 'workflow_header' %>

<p>This membership request has expired.</p>

<p>You may apply for a new membership type from <%= link_to 'the dashboard', dashboard_path %>.</p>

<%= render 'workflow_footer' %>

app/views/membership_requests/workflow_new.html.erb
<%= render 'workflow_header' %>

<%= form_tag do %>
    <div class="field">
      <p>Can you tell us a bit about your venture?</p>
      <%= text_area_tag(:info, @membership_request.info) %>
    </div>

    <div class="field">
      <p>When would you like to start your membership?</p>
      <%= date_select(:startdate, :startdate, default: Date.today, with_css_classes: true, discard_day: true) %>
    </div>

    <%= submit_tag('Continue', id: 'membership_request_info_submit') %>
<% end %>

<%= render 'workflow_footer' %>

app/views/membership_requests/workflow_payment_required.html.erb
<%= render 'workflow_header' %>

<% if @membership_type.autoapprove %>
    <p>Thank you for applying to become a Bloom <%= @membership_request.membership_type.name %>! Please click below to arrange payment.</p>
<% else %>
    <p>Thank you for applying to become a Bloom <%= @membership_request.membership_type.name %>! We're happy to inform you that your application has been accepted. Please click below to arrange payment.</p>
<% end %>

<% if @membership_type.recurring %>
  <%= form_tag(controller: 'membership_payments', action: 'capture_subscription', method: 'post') do %>
      <input type="hidden" value="<%= @membership_request.id %>" name="membership_request_id">
      <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
              data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
              data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
              data-name="Bloom <%= @membership_type.name %> Subscription"
              data-description="Subscribe (<%= number_to_currency(@membership_type.price/100) %> per month)"
              data-panel-label="Subscribe"
              data-label="Subscribe"
              data-email="<%= @membership_request.user.email %>"
              data-amount="<%= @membership_type.price %>"
              data-allow-remember-me="false">
      </script>
  <% end %>
<% else %>
  <%= form_tag(controller: 'membership_payments', action: 'capture_single', method: 'post') do %>
      <input type="hidden" value="<%= @membership_request.id %>" name="membership_request_id">
      <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
              data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
              data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
              data-name="Bloom <%= @membership_type.name %>"
              data-description="Pay for a semester (<%= number_to_currency(@membership_type.price/100) %>)"
              data-panel-label="Pay"
              data-label="Pay"
              data-email="<%= @membership_request.user.email %>"
              data-amount="<%= @membership_type.price %>"
              data-allow-remember-me="false">
      </script>
  <% end %>
<% end %>

<%= render 'workflow_footer' %>

app/views/membership_requests/workflow_pending_decision.html.erb
<%= render 'workflow_header' %>
<% if @membership_type.name == 'freelancer' %>
    <p>
      Thank you for submitting your application to become a Bloom Freelancer!
    </p>
    <p>
      A Bloom team member will be in contact with you in the next few days to arrange an induction session and set you
      up with a 24/7 access card for use out of business hours.
    </p>
    <ul>
      <li>Like the <a href="http://facebook.com/BloomPerth">Bloom Facebook Page</a> and subscribe to our events
        feed
      </li>
      <li>Join the <a href="http://facebook.com/groups/bloom.community">Bloom Community</a> and
        <a href="http://facebook.com/groups/867349346651609">Bloom Member</a> Facebook Groups
      </li>
      <li>
        Come along to our next monthly Friday community pitch night & drinks
      </li>
    </ul>
    <p>Welcome to Bloom!</p>
<% else %>
    <p>Thank you for submitting your application for a Bloom <%= @membership_request.membership_type.name %>!</p>
    <p>To be accepted as a member you need to complete a lean canvas and pitch at one of our monthly pitch nights.
      <% if !@next_pitching_night.nil? %>
          Our next pitch night is happening
          on <%= DateTime.parse(@next_pitching_night['start_time']).strftime('%d %B') %>. Sign up to pitch
          <a href="http://facebook.com/events/<%= @next_pitching_night['id'] %>">here</a>.
      <% else %>
          Watch our <a href="https://www.facebook.com/BloomPerth/events">events feed</a> to sign up for the next pitching
          night.
      <% end %>
    </p>
    <p>
      To help you get ready to pitch come to our event "Your Business Model on a Page" to help you prepare your lean
      canvas.
      <% if !@next_leancanvas_night.nil? %>
          The next event is happening on <%= DateTime.parse(@next_leancanvas_night['start_time']).strftime('%d %B') %>
          and you can sign up to pitch
          <a href="http://facebook.com/events/<%= @next_leancanvas_night['id'] %>">here</a>.
      <% end %>
    </p>
    <p>
      We also run "Preparing to Pitch" events so you know what should go in your 3 minute pitch to become a member.
      <% if !@next_preparing_to_pitch_night.nil? %>
          The next "Preparing to Pitch" event is happening
          on <%= DateTime.parse(@next_preparing_to_pitch_night['start_time']).strftime('%d %B') %> and you can
          sign up to pitch
          <a href="http://facebook.com/events/<%= @next_preparing_to_pitch_night['id'] %>">here</a>.
      <% end %>
    </p>
    <p>
      You can always find the latest events on our <a href="http://facebook.com/BloomPerth">Facebook page</a>.
    </p>
<% end %>
<%= render 'workflow_footer' %>

app/views/membership_requests/workflow_rejected.html.erb
<%= render 'workflow_header' %>

<p>Thank you for applying to become a Bloom <%= @membership_request.membership_type.name %>. We're sorry to inform you that we're not able to accept your application at this time.</p>

<p>We would like to encourage you to become a Bloom Community Member - you can get access to all the workshops and advisors you need to develop your idea and apply again.</p>

<%= render 'workflow_footer' %>