config/routes.rb
Rails.application.routes.draw do
  get '/oauth_apply' => 'application#oauth_apply_callback_generator'

  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}

  resources :user_profiles, only: [:new, :create]
  resources :job_postings
  resources :booking_access_tokens, only: [:new, :create, :show, :index] do
    collection do
      get :signup
    end
  end
  resource :wifi, only: [:show, :update], controller: 'wifi'

  scope 'membership_payments', controller: :membership_payments do
    post 'stripe_webhook'
    post 'capture_single'
    post 'capture_subscription'
    post 'process_cancel_subscription'
    get 'payment_confirmation'
    get 'pay_single'
    get 'cancel_subscription'
  end

  resources :membership_requests, only: [:new, :show, :create] do
    member do
      MembershipRequest.workflow_spec.states.keys.each do |state|
        get "stage/#{state}" => "membership_requests#workflow_#{state}", as: "workflow_#{state}"
        post "stage/#{state}" => "membership_requests#workflow_#{state}", as: "workflow_submit_#{state}"
      end
    end
  end

  namespace :api do
    resources :users, only: [:index]
  end

  get 'booking/:name/new' => 'booking#new'
  post 'booking/:name/pay' => 'booking#pay'
  get 'booking/:id/confirmation' => 'booking#confirmation'

  scope 'api', controller: :api do
    get 'st_cats_admin' => 'api#profiles_csv'
    post 'user_auth_token'
    post 'profiles/:id' => 'api#get_profile_info'
    post 'profiles/:id/update' => 'api#update_profile_info'
    #get 'profiles/:id/profile_image_upload_url' => 'api#profile_image_upload_url'
  end

  get '/admin/membership_requests/:id', to: redirect('/admin/membership_request/%{id}') # Backwards compatibility
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'dashboard' => 'welcome#dashboard'
  root 'welcome#index'
end

app/models/job_posting.rb
class JobPosting < ActiveRecord::Base
  belongs_to :user
  validate do |job_posting|
    if job_posting.expiry <= Date.today
      job_posting.errors[:expiry] = 'Must expire in the future'
    end
  end

  def allows_editing(user)
     !user.nil? and (user.id == self.user_id or user.manager?)
  end
end

app/controllers/job_postings_controller.rb
class JobPostingsController < ApplicationController
  before_action :set_job_posting, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :authenticate_editor, only: [:edit, :update, :destroy]

  # GET /job_postings
  # GET /job_postings.json
  def index
    @job_postings = JobPosting.where('expiry <= ? and closed = false', Date.today)
  end

  # GET /job_postings/1
  # GET /job_postings/1.json
  def show
  end

  # GET /job_postings/new
  def new
    @job_posting = JobPosting.new
  end

  # GET /job_postings/1/edit
  def edit
  end

  # POST /job_postings
  # POST /job_postings.json
  def create
    @job_posting = JobPosting.new(job_posting_params)
    @job_posting.user_id = current_user.id

    respond_to do |format|
      if @job_posting.save
        format.html { redirect_to @job_posting, notice: 'Job posting was successfully created.' }
        format.json { render :show, status: :created, location: @job_posting }
      else
        format.html { render :new }
        format.json { render json: @job_posting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_postings/1
  # PATCH/PUT /job_postings/1.json
  def update
    respond_to do |format|
      if @job_posting.update(job_posting_params)
        format.html { redirect_to @job_posting, notice: 'Job posting was successfully updated.' }
        format.json { render :show, status: :ok, location: @job_posting }
      else
        format.html { render :edit }
        format.json { render json: @job_posting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_postings/1
  # DELETE /job_postings/1.json
  def destroy
    @job_posting.destroy
    respond_to do |format|
      format.html { redirect_to job_postings_url, notice: 'Job posting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def authenticate_editor
    if not @job_posting.allows_editing(current_user)
      render 404
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_job_posting
    @job_posting = JobPosting.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def job_posting_params
    params.require(:job_posting).permit(:description, :closed, :title, :expiry, :requirements)
  end
end

app/helpers/job_postings_helper.rb
module JobPostingsHelper
end

app/views/job_postings/_form.html.erb
<%= form_for(@job_posting) do |f| %>
    <% if @job_posting.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@job_posting.errors.count, "error") %> prohibited this job_posting from being saved:</h2>

          <ul>
            <% @job_posting.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description %>
    </div>
    <div class="field">
      <%= f.label :requirements %><br>
      <%= f.text_field :requirements %>
    </div>
    <div class="field">
      <%= f.label :expiry %><br>
      <%= f.date_select :expiry, with_css_classes: true, order: [:day, :month, :year] %>
    </div>
    <div class="field">
      <%= f.label :closed %><br>
      <%= f.check_box :closed %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/job_postings/edit.html.erb
<h1>Editing Job Posting</h1>

<%= render 'form' %>

<%= link_to 'Show', @job_posting %> |
<%= link_to 'Back', job_postings_path %>

app/views/job_postings/index.html.erb
<p id="notice"><%= notice %></p>

<h1 style="display: inline-block">Listing Job Postings</h1>
<%= link_to 'New Job posting', new_job_posting_path %>

<table>
  <thead>
  <tr>
    <th id="job-listing-header-user">User</th>
    <th>Description</th>
    <th>Title</th>
    <th>Expiry</th>
    <th>Requirements</th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @job_postings.each do |job_posting| %>
      <tr>
        <td><%= job_posting.user.name %></td>
        <td><%= job_posting.description %></td>
        <td><%= job_posting.title %></td>
        <td><%= job_posting.expiry %></td>
        <td><%= job_posting.requirements %></td>
        <td><%= link_to 'Show', job_posting %>
          <% if job_posting.allows_editing(current_user) %>
            <%= link_to 'Edit', edit_job_posting_path(job_posting) %>
            <%= link_to 'Destroy', job_posting, method: :delete, data: {confirm: 'Are you sure?'} %>
        <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= javascript_include_tag 'job_postings' %>

app/views/job_postings/new.html.erb
<h1>New Job Posting</h1>

<%= render 'form' %>

<%= link_to 'Back', job_postings_path %>

app/views/job_postings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @job_posting.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @job_posting.user %>
</p>

<p>
  <strong>Title:</strong>
  <%= @job_posting.title %>
</p>

<p>
  <strong>Expiry:</strong>
  <%= @job_posting.expiry %>
</p>

<p>
  <strong>Requirements:</strong>
  <%= @job_posting.requirements %>
</p>

<%= link_to 'Edit', edit_job_posting_path(@job_posting) %> |
<%= link_to 'Back', job_postings_path %>