config/routes.rb
Rails.application.routes.draw do
  get '/oauth_apply' => 'application#oauth_apply_callback_generator'

  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}

  resources :user_profiles, only: [:new, :create]
  resources :job_postings
  resources :booking_access_tokens, only: [:new, :create, :show, :index] do
    collection do
      get :signup
    end
  end
  resource :wifi, only: [:show, :update], controller: 'wifi'

  scope 'membership_payments', controller: :membership_payments do
    post 'stripe_webhook'
    post 'capture_single'
    post 'capture_subscription'
    post 'process_cancel_subscription'
    get 'payment_confirmation'
    get 'pay_single'
    get 'cancel_subscription'
  end

  resources :membership_requests, only: [:new, :show, :create] do
    member do
      MembershipRequest.workflow_spec.states.keys.each do |state|
        get "stage/#{state}" => "membership_requests#workflow_#{state}", as: "workflow_#{state}"
        post "stage/#{state}" => "membership_requests#workflow_#{state}", as: "workflow_submit_#{state}"
      end
    end
  end

  namespace :api do
    resources :users, only: [:index]
  end

  get 'booking/:name/new' => 'booking#new'
  post 'booking/:name/pay' => 'booking#pay'
  get 'booking/:id/confirmation' => 'booking#confirmation'

  scope 'api', controller: :api do
    get 'st_cats_admin' => 'api#profiles_csv'
    post 'user_auth_token'
    post 'profiles/:id' => 'api#get_profile_info'
    post 'profiles/:id/update' => 'api#update_profile_info'
    #get 'profiles/:id/profile_image_upload_url' => 'api#profile_image_upload_url'
  end

  get '/admin/membership_requests/:id', to: redirect('/admin/membership_request/%{id}') # Backwards compatibility
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'dashboard' => 'welcome#dashboard'
  root 'welcome#index'
end

app/models/booking_access_token.rb
class BookingAccessToken < ActiveRecord::Base
  has_many :booking_access_token_resources, :dependent => :delete_all
  has_many :user_booking_access_tokens
  validate do |booking_access_token|
    if booking_access_token.expiry < Date.today
      booking_access_token.errors[:expiry] = 'Must expire in the future'
    end
    if booking_access_token.signup_expiry < Date.today
      booking_access_token.errors[:signup_expiry] = 'Must expire in the future'
    end
    if booking_access_token.discount < 0 or booking_access_token.discount > 100
      booking_access_token.errors[:discount] = 'Discount should be a positive percentage'
    end
  end
end

app/controllers/booking_access_tokens_controller.rb
class BookingAccessTokensController < ApplicationController
  before_action :authenticate_user!, only: [:signup]

  def signup
    @token = BookingAccessToken.find_by_token(params[:uuid])
    if @token.nil?
      head 404
    elsif @token.signup_expiry < Date.today
      render 'token_expired'
    else
      if UserBookingAccessToken.find_by_booking_access_token_id(@token.id).nil?
        UserBookingAccessToken.create!(user_id: current_user.id, booking_access_token_id: @token.id)
      end
      flash[:notice] = 'Booking access added successfully'
      redirect_to '/booking/serious/new'
    end
  end

  def index
    head 422 and return if current_user.nil? or not current_user.manager?
    @tokens = BookingAccessToken.where('expiry >= ?', Date.today)
  end

  def show
    head 422 and return if current_user.nil? or not current_user.manager?
    @token = BookingAccessToken.find_by_id!(params[:id])
  end

  def new
    head 422 and return if current_user.nil? or not current_user.manager?
    @token = BookingAccessToken.new
  end

  def create
    head 422 and return if current_user.nil? or not current_user.manager?
    if params[:resources].empty?
      flash[:error] = 'At least one resource must be selected'
      render :new and return
    end
    @token = BookingAccessToken.new(params.require(:booking_access_token).permit(:discount, :expiry, :signup_expiry))
    @token.token = SecureRandom.uuid

    if @token.save
      params[:resources].each do |resource_id|
        @token_resource = BookingAccessTokenResource.new(resource_id: resource_id, booking_access_token_id: @token.id)
        if not @token_resource.save
          flash[:error] = 'Unknown resource'
          @token.delete
          render :new and return
        end
      end
      redirect_to @token, notice: 'Token was successfully created with url.'
    else
      render :new
    end
  end
end

app/helpers/booking_access_tokens_helper.rb
module BookingAccessTokensHelper
end

app/views/booking_access_tokens/index.html.erb
<h1 style="display: inline-block">Currently unexpired booking access tokens</h1> <%= link_to 'Create new token', booking_access_token_path(:new) %>
<ul>
  <% @tokens.each do |token| %>
      <li><%= link_to token.token, booking_access_token_path(token) %></li>
  <% end %>
</ul>

app/views/booking_access_tokens/new.html.erb
<h1>New booking token generator</h1>

<%= form_for(@token) do |f| %>
    <% if @token.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@token.errors.count, "error") %> prohibited this token from being saved:</h2>

          <ul>
            <% @token.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :discount %>
      <%= f.text_field :discount, placeholder: 'Discount (%)' %>
    </div>
    <div class="field">
      <%= f.label :signup_expiry %>
      <p>The discount token cannot have new signups after this date</p>
      <%= f.date_select :signup_expiry, with_css_classes: true, order: [:day, :month, :year] %>
    </div>
    <div class="field">
      <%= f.label :expiry %>
      <p>The discount will expire at this date</p>
      <%= f.date_select :expiry, with_css_classes: true, order: [:day, :month, :year] %>
    </div>
    <div class="field">
      <p>Select all of the resources you want the discount to be applied to.</p>
      <%= select_tag 'resources', options_from_collection_for_select(Resource.all, "id", "full_name"), :multiple => true %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/booking_access_tokens/show.html.erb
<h1>Booking access token</h1>
<p>Discount: <%= @token.discount %>%</p>
<p>Expiry: <%= @token.expiry %></p>
<p>Signup expiry: <%= @token.signup_expiry %></p>
<p>Link: <%= request.protocol + request.host_with_port + signup_booking_access_tokens_path(uuid: @token.token) %></p>
<h4>Resources</h4>
<ul>
  <% BookingAccessTokenResource.where(booking_access_token_id: @token.id).each do |token_resource| %>
      <li>
        <%= token_resource.resource.full_name %>
      </li>
  <% end %>
</ul>

app/views/booking_access_tokens/token_expired.html.erb
<h1>Oops! Looks like the link you followed has expired</h1>

Please contact alexandra@bloom.org.au if you think this is in error.